{{- $bucketStorageTypes :=  list "s3" "gcs" -}}

{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-medusa-config-k8ssandra
  labels: {{ include "k8ssandra.labels" . | indent 4 }}
data:
  medusa.ini: |-
    [cassandra]
    # The start and stop commands are not applicable in k8s.
    stop_cmd = /etc/init.d/cassandra stop
    start_cmd = /etc/init.d/cassandra start
  {{- if not .Values.cassandra.auth.enabled }}
    cql_username = cassandra
    cql_password = cassandra
  {{- end}}
    check_running = nodetool version

    [storage]
{{- if eq .Values.backupRestore.medusa.storage "s3" }}
    storage_provider = s3
    {{- if .Values.backupRestore.medusa.storage_properties.region }}
    region = {{ .Values.backupRestore.medusa.storage_properties.region }}
    {{- end}}
{{- else if eq .Values.backupRestore.medusa.storage "gcs" }}
    storage_provider = gcs
{{- else if eq .Values.backupRestore.medusa.storage "s3_compatible" }}
    storage_provider = s3_compatible
    {{- if .Values.backupRestore.medusa.storage_properties.region }}
    region = {{ .Values.backupRestore.medusa.storage_properties.region }}
    {{- end}}
    host = {{ .Values.backupRestore.medusa.storage_properties.host }}
    port = {{ .Values.backupRestore.medusa.storage_properties.port }}
    secure = {{ .Values.backupRestore.medusa.storage_properties.secure }}
{{- end }}
    bucket_name = {{ .Values.backupRestore.medusa.bucketName }}
    # TODO The file name needs to be parameterized. In the current set up it comes from the secret.
    key_file = /etc/medusa-secrets/medusa_s3_credentials
{{- if and .Values.backupRestore.medusa.multiTenant (has .Values.backupRestore.medusa.storage $bucketStorageTypes)}}
    prefix = {{ .Values.clusterName }}.{{ .Release.Namespace }}
{{- end }}

    [grpc]
    enabled = 1

    [kubernetes]
    cassandra_url = http://localhost:7373/jolokia/
    enabled = 1

    [logging]
    level = DEBUG
  {{- end }}