# Default values for k8ssandra-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: k8ssandra
clusterName: k8ssandra
datacenterName: dc1
size: 1

# Configuration regarding configuration of repair services
repair:
  # Reaper repair service and UI
  reaper:
    enabled: true
    jmx:
      username: ""
      password: ""
    operator:
      enabled: true

# Support for accessing the various web-interfaces via K8s ingress controllers.
# Depending on the ingress available in your clsuter enable the appropriate
# secion.
ingress:
  traefik:
    # Set to `true` to enable the templating of Traefik ingress custom resources
    enabled: false

    # Repair service
    repair: 
      # Note this will **only** work if `traefik.enabled` is also `true`
      enabled: true

      # Name of the Traefik entrypoints where we want to source traffic.
      entrypoints: 
        - web

      # Hostname Traefik should use for matching requests.
      host: repair.k8ssandra.cluster.local

    cassandra:
      enabled: false
      entrypoints: 
        - cassandra
