# Default values for k8ssandra-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: k8ssandra
clusterName: k8ssandra
datacenterName: dc1
size: 1

k8ssandra:
  # The k8ssandra chart installs operators with cluster scope. It can be installed in a
  # different namespace. The namespace and name of the k8ssandra chart release are needed
  # to configure some resources like the Grafana data source.
  namespace: default
  name: k8ssandra

# Configuration regarding configuration of repair services
repair:
  # Reaper repair service and UI
  reaper:
    enabled: true
    jmx:
      username: ""
      password: ""
    operator:
      enabled: true

backupRestore:
  medusa:
    # If enabled, bucketName and bucketSecret must be defined.
    enabled: false

    # Accepted values are s3 and gcs
    storage: s3

    # Must be set to the name of the remote storage bucket where backups will be stored.
    bucketName: ""

    # Must be set and specify the name of the secret that stores the key file for Google
    # Cloud or AWS
    bucketSecret: ""

# Support for accessing the various web-interfaces via K8s ingress controllers.
# Depending on the ingress available in your cluster enable the appropriate
# section.
ingress:
  traefik:
    # Set to `true` to enable the templating of Traefik ingress custom resources
    enabled: false

    # Repair service
    repair: 
      # Note this will **only** work if `ingress.traefik.enabled` is also `true`
      enabled: true

      # Name of the Traefik entrypoints where we want to source traffic.
      entrypoints: 
        - web

      # Hostname Traefik should use for matching requests.
      host: repair.k8ssandra.cluster.local

    # Cassandra native transport ingress support
    cassandra:
      # Note this will **only** work if `ingress.traefik.enabled` is also `true`
      enabled: false

      # Name of the Traefik entrypoints for source traffic
      entrypoints: 
        - cassandra

    # Monitoring web interfaces for Promtheus and Grafana
    monitoring:
      grafana:
        # Note this will **only** work if `ingress.traefik.enabled` is also `true`
        enabled: true

        # Name of the Traefik entrypoints where we want to source traffic.
        entrypoints:
          - web

        # Hostname Traefik should use for matching requests.
        host: grafana.k8ssandra.cluster.local

      prometheus:
        # Note this will **only** work if `ingress.traefik.enabled` is also `true`
        enabled: true

        # Name of the Traefik entrypoints where we want to source traffic.
        entrypoints:
          - web

        # Hostname Traefik should use for matching requests.
        host: prometheus.k8ssandra.cluster.local

grafana:
  adminUser: admin
  adminPassword: secret
