kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: k8ssandra-{{ .Release.Name }}-repair
spec:
  rules:
    - host: repair.{{ .Release.Name }}.k8ssandra
      http:
        paths:
          - path: /
            backend:
              # TODO - update with service values from for Reaper
              serviceName: {{ .Release.Name }}-reaper-k8ssandra-reaper-service
              servicePort: 80
