apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: cass-operator
      cassandra.datastax.com/prom-metrics: "true"
    matchExpressions:
      - {key: cassandra.datastax.com/cluster, operator: Exists}
      - {key: cassandra.datastax.com/datacenter, operator: Exists}
  targetLabels:
  - cassandra.datastax.com/cluster
  - cassandra.datastax.com/datacenter
  endpoints:
  - port: prometheus
