---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .Values.grafana.name }}
spec:
  ingress:
    enabled: false
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: {{ .Values.grafana.adminPassword }}
      admin_user: {{ .Values.grafana.adminUsername }}
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
